<a href="https://colab.research.google.com/github/VarshithaKrishna/ML/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Demonstrate the following data preprocessing tasks using python libraries. a) Dealing with categorical data b) Scaling the features c) Splitting dataset into Training and Testing Sets

In [ ]:
#It refers to the process of converting categorical or textual data into
#numerical format, so that it can be used as input for algorithms to process.
#The reason for encoding is that most machine learning algorithms work with
#numbers and not with text or categorical variables
#One-Hot Encoding is another popular technique for treating categorical variables.
#It simply creates additional features based on the number of unique values in the categorical feature.
#Every unique value in the category will be added as a feature.
#One-Hot Encoding is the process of creating dummy variables
#Importing libraries and reading dataset
import pandas as pd
df=pd.read_csv('/content/house-prices.csv')
df

Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0       1  114300  1790         2          2       2    No         East
1       2  114200  2030         4          2       3    No         East
2       3  114800  1740         3          2       1    No         East
3       4   94700  1980         3          2       3    No         East
4       5  119800  2130         3          3       3    No         East
..    ...     ...   ...       ...        ...     ...   ...          ...
123   124  119700  1900         3          3       3   Yes         East
124   125  147900  2160         4          3       3   Yes         East
125   126  113500  2070         2          2       2    No        North
126   127  149900  2020         3          3       1    No         West
127   128  124600  2250         3          3       4    No        North

[128 rows x 8 columns]

In [ ]:
#dummy variables
#In this, we have four categories so had four columns for four different dummy variables.
dummies=pd.get_dummies(df.Bedrooms)
dummies


2  3  4  5
0    1  0  0  0
1    0  0  1  0
2    0  1  0  0
3    0  1  0  0
4    0  1  0  0
..  .. .. .. ..
123  0  1  0  0
124  0  0  1  0
125  1  0  0  0
126  0  1  0  0
127  0  1  0  0

[128 rows x 4 columns]

In [ ]:
# Merging dummy variables
merged=pd.concat([df,dummies],axis='columns')
merged

Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood  2  3  \
0       1  114300  1790         2          2       2    No         East  1  0   
1       2  114200  2030         4          2       3    No         East  0  0   
2       3  114800  1740         3          2       1    No         East  0  1   
3       4   94700  1980         3          2       3    No         East  0  1   
4       5  119800  2130         3          3       3    No         East  0  1   
..    ...     ...   ...       ...        ...     ...   ...          ... .. ..   
123   124  119700  1900         3          3       3   Yes         East  0  1   
124   125  147900  2160         4          3       3   Yes         East  0  0   
125   126  113500  2070         2          2       2    No        North  1  0   
126   127  149900  2020         3          3       1    No         West  0  1   
127   128  124600  2250         3          3       4    No        North  0  1   

     4  5  
0    0  0  
1    1  0  
2    0  0  
3    0  0  
4    0  0  
..  .. ..  
123  0  0  
124  1  0  
125  0  0  
126  0  0  
127  0  0  

[128 rows x 12 columns]

In [ ]:
#Dropping ‘Home’ column
final = merged.drop(['Home'], axis=1)
final

Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood  2  3  4  5
0    114300  1790         2          2       2    No         East  1  0  0  0
1    114200  2030         4          2       3    No         East  0  0  1  0
2    114800  1740         3          2       1    No         East  0  1  0  0
3     94700  1980         3          2       3    No         East  0  1  0  0
4    119800  2130         3          3       3    No         East  0  1  0  0
..      ...   ...       ...        ...     ...   ...          ... .. .. .. ..
123  119700  1900         3          3       3   Yes         East  0  1  0  0
124  147900  2160         4          3       3   Yes         East  0  0  1  0
125  113500  2070         2          2       2    No        North  1  0  0  0
126  149900  2020         3          3       1    No         West  0  1  0  0
127  124600  2250         3          3       4    No        North  0  1  0  0

[128 rows x 11 columns]

In [ ]:
#Dropping one dummy(2) column
final = final.drop([2], axis=1)
final

Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood  3  4  5
0    114300  1790         2          2       2    No         East  0  0  0
1    114200  2030         4          2       3    No         East  0  1  0
2    114800  1740         3          2       1    No         East  1  0  0
3     94700  1980         3          2       3    No         East  1  0  0
4    119800  2130         3          3       3    No         East  1  0  0
..      ...   ...       ...        ...     ...   ...          ... .. .. ..
123  119700  1900         3          3       3   Yes         East  1  0  0
124  147900  2160         4          3       3   Yes         East  0  1  0
125  113500  2070         2          2       2    No        North  0  0  0
126  149900  2020         3          3       1    No         West  1  0  0
127  124600  2250         3          3       4    No        North  1  0  0

[128 rows x 10 columns]

In [ ]:
#dropping multiple variables
X = final.drop(['Brick', 'Neighborhood'], axis=1)
X

Price  SqFt  Bedrooms  Bathrooms  Offers  3  4  5
0    114300  1790         2          2       2  0  0  0
1    114200  2030         4          2       3  0  1  0
2    114800  1740         3          2       1  1  0  0
3     94700  1980         3          2       3  1  0  0
4    119800  2130         3          3       3  1  0  0
..      ...   ...       ...        ...     ... .. .. ..
123  119700  1900         3          3       3  1  0  0
124  147900  2160         4          3       3  0  1  0
125  113500  2070         2          2       2  0  0  0
126  149900  2020         3          3       1  1  0  0
127  124600  2250         3          3       4  1  0  0

[128 rows x 8 columns]

In [ ]:
data=pd.read_excel("/content/DM2.xlsx")
data

Index    Country  Age  Salary
0       0      India   25   35000
1       1        USA   27   40000
2       2      Japan   50   54000
3       3        USA   35   57000
4       4      Japan   40   60000
5       5      India   35   58000
6       6      China   41   52000
7       7    Germany   48   79000
8       8  Singapore   50   83000
9       9    Malasia   37   59000
10     10      Dubai   21   24000
11     11      China   29   60000
12     12    Germany   63   70000

In [ ]:
dataset=pd.read_excel("/content/Book1.xlsx")
print(dataset)
x=dataset.iloc[:,:-1] # it takes all rows all columns except the last column in the dataset
y=dataset.iloc[:,-1].values #it takes all rows of last column in the dataset
print(x)
print(y)

In [ ]:
from sklearn.impute import SimpleImputer
import numpy as np
imp=SimpleImputer(missing_values=np.nan,strategy='mean')
x=imp.fit_transform(x)
y=y.reshape(-1,1)
y=imp.fit_transform(y)
y=y.reshape(-1)
x,y

(array([[22.],
        [25.],
        [45.],
        [39.],
        [43.],
        [60.]]),
 array([23000., 55000., 45750., 70000., 35000., 45750.]))

In [ ]:
#label encoder
#import label encoder
from sklearn import preprocessing as p
from sklearn.preprocessing import LabelEncoder
df=pd.read_excel("/content/DM2.xlsx")
#le object knows how to understand word labels
le=p.LabelEncoder()
#encode labels in column  'country'
df['Country']=le.fit_transform(df['Country'])
df


Index  Country  Age  Salary
0       0        3   25   35000
1       1        7   27   40000
2       2        4   50   54000
3       3        7   35   57000
4       4        4   40   60000
5       5        3   35   58000
6       6        0   41   52000
7       7        2   48   79000
8       8        6   50   83000
9       9        5   37   59000
10     10        1   21   24000
11     11        0   29   60000
12     12        2   63   70000

In [ ]:
#one hot encoder
#importing libraries
from sklearn.preprocessing import OneHotEncoder
#retrieving the data
data=pd.read_excel("/content/DM2.xlsx")
#converting type of columns to category
data['Country']=data['Country'].astype('category')
#Assigning numerical values and storing it in another columns
data['Country_new']=data['Country'].cat.codes
#creating an instance of one_hot_encoder
enc=OneHotEncoder()
#passing encoded columns
enc_data=pd.DataFrame(enc.fit_transform(data[['Country']]).toarray())
#merge with main dataset
new_df=data.join(enc_data)
new_df

Index    Country  Age  Salary  Country_new    0    1    2    3    4    5  \
0       0      India   25   35000            3  0.0  0.0  0.0  1.0  0.0  0.0   
1       1        USA   27   40000            7  0.0  0.0  0.0  0.0  0.0  0.0   
2       2      Japan   50   54000            4  0.0  0.0  0.0  0.0  1.0  0.0   
3       3        USA   35   57000            7  0.0  0.0  0.0  0.0  0.0  0.0   
4       4      Japan   40   60000            4  0.0  0.0  0.0  0.0  1.0  0.0   
5       5      India   35   58000            3  0.0  0.0  0.0  1.0  0.0  0.0   
6       6      China   41   52000            0  1.0  0.0  0.0  0.0  0.0  0.0   
7       7    Germany   48   79000            2  0.0  0.0  1.0  0.0  0.0  0.0   
8       8  Singapore   50   83000            6  0.0  0.0  0.0  0.0  0.0  0.0   
9       9    Malasia   37   59000            5  0.0  0.0  0.0  0.0  0.0  1.0   
10     10      Dubai   21   24000            1  0.0  1.0  0.0  0.0  0.0  0.0   
11     11      China   29   60000            0  1.0  0.0  0.0  0.0  0.0  0.0   
12     12    Germany   63   70000            2  0.0  0.0  1.0  0.0  0.0  0.0   

      6    7  
0   0.0  0.0  
1   0.0  1.0  
2   0.0  0.0  
3   0.0  1.0  
4   0.0  0.0  
5   0.0  0.0  
6   0.0  0.0  
7   0.0  0.0  
8   1.0  0.0  
9   0.0  0.0  
10  0.0  0.0  
11  0.0  0.0  
12  0.0  0.0

In [ ]:
import pandas as pd
df=pd.read_csv("/content/wine.csv",header=None,usecols=[0,1])
df.columns=['Alcohol','Malic_Acid']
df.head()

Alcohol  Malic_Acid
0    14.23        1.71
1    13.20        1.78
2    13.16        2.36
3    14.37        1.95
4    13.24        2.59

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaling=MinMaxScaler()
scaling.fit_transform(df[['Alcohol','Malic_Acid']])

array([[0.88429752, 0.        ],
       [0.03305785, 0.07954545],
       [0.        , 0.73863636],
       [1.        , 0.27272727],
       [0.0661157 , 1.        ]])

In [ ]:
from sklearn.preprocessing import StandardScaler
scaling=StandardScaler()
scaling.fit_transform(df[['Alcohol','Malic_Acid']])

array([[ 1.08997918, -1.07836773],
       [-0.81286583, -0.87324344],
       [-0.88676272,  0.82635788],
       [ 1.3486183 , -0.37508443],
       [-0.73896893,  1.50033771]])

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
df=pd.read_csv("/content/house.csv")
columns=['bedrooms','bathrooms','sqft_living','sqft_lot','floors','price']
df=df.loc[:,columns]
print(df.head())

   bedrooms  bathrooms  sqft_living  sqft_lot  floors   price
0         3       1.00         1180      5650       1  221900
1         3       2.25         2570      7242       2  538000
2         2       1.00          770     10000       1  180000
3         4       3.00         1960      5000       1  604000
4         3       2.00         1680      8080       1  510000


In [ ]:
features=['bedrooms','bathrooms','sqft_living','sqft_lot','floors']
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.75,random_state=0)


In [ ]:
print(x_train.count())
print(y_train.count())
print(x_test.count())
print(y_test.count())

bedrooms       3
bathrooms      3
sqft_living    3
sqft_lot       3
floors         3
dtype: int64
3
bedrooms       2
bathrooms      2
sqft_living    2
sqft_lot       2
floors         2
dtype: int64
2
